# Depencencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               Remember 12?
tagline:
description:
url:                 https://phongphan.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Phongphan Phuttha
  url:               https://phongphan.github.io
  email:             phongphan.p@@gmail.com

# Custom vars
version:             1.0.0
